/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as RecreationRouteImport } from './routes/recreation'
import { Route as MasterPlanRouteImport } from './routes/master-plan'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AquariumRouteImport } from './routes/aquarium'
import { Route as AgricultureRouteImport } from './routes/agriculture'
import { Route as IndexRouteImport } from './routes/index'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const RecreationRoute = RecreationRouteImport.update({
  id: '/recreation',
  path: '/recreation',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPlanRoute = MasterPlanRouteImport.update({
  id: '/master-plan',
  path: '/master-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AquariumRoute = AquariumRouteImport.update({
  id: '/aquarium',
  path: '/aquarium',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultureRoute = AgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aquarium': typeof AquariumRoute
  '/contact': typeof ContactRoute
  '/hospitality': typeof HospitalityRoute
  '/investment': typeof InvestmentRoute
  '/master-plan': typeof MasterPlanRoute
  '/recreation': typeof RecreationRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aquarium': typeof AquariumRoute
  '/contact': typeof ContactRoute
  '/hospitality': typeof HospitalityRoute
  '/investment': typeof InvestmentRoute
  '/master-plan': typeof MasterPlanRoute
  '/recreation': typeof RecreationRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agriculture': typeof AgricultureRoute
  '/aquarium': typeof AquariumRoute
  '/contact': typeof ContactRoute
  '/hospitality': typeof HospitalityRoute
  '/investment': typeof InvestmentRoute
  '/master-plan': typeof MasterPlanRoute
  '/recreation': typeof RecreationRoute
  '/sustainability': typeof SustainabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agriculture'
    | '/aquarium'
    | '/contact'
    | '/hospitality'
    | '/investment'
    | '/master-plan'
    | '/recreation'
    | '/sustainability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agriculture'
    | '/aquarium'
    | '/contact'
    | '/hospitality'
    | '/investment'
    | '/master-plan'
    | '/recreation'
    | '/sustainability'
  id:
    | '__root__'
    | '/'
    | '/agriculture'
    | '/aquarium'
    | '/contact'
    | '/hospitality'
    | '/investment'
    | '/master-plan'
    | '/recreation'
    | '/sustainability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgricultureRoute: typeof AgricultureRoute
  AquariumRoute: typeof AquariumRoute
  ContactRoute: typeof ContactRoute
  HospitalityRoute: typeof HospitalityRoute
  InvestmentRoute: typeof InvestmentRoute
  MasterPlanRoute: typeof MasterPlanRoute
  RecreationRoute: typeof RecreationRoute
  SustainabilityRoute: typeof SustainabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recreation': {
      id: '/recreation'
      path: '/recreation'
      fullPath: '/recreation'
      preLoaderRoute: typeof RecreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-plan': {
      id: '/master-plan'
      path: '/master-plan'
      fullPath: '/master-plan'
      preLoaderRoute: typeof MasterPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aquarium': {
      id: '/aquarium'
      path: '/aquarium'
      fullPath: '/aquarium'
      preLoaderRoute: typeof AquariumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agriculture': {
      id: '/agriculture'
      path: '/agriculture'
      fullPath: '/agriculture'
      preLoaderRoute: typeof AgricultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgricultureRoute: AgricultureRoute,
  AquariumRoute: AquariumRoute,
  ContactRoute: ContactRoute,
  HospitalityRoute: HospitalityRoute,
  InvestmentRoute: InvestmentRoute,
  MasterPlanRoute: MasterPlanRoute,
  RecreationRoute: RecreationRoute,
  SustainabilityRoute: SustainabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
